USE [master]
GO
/****** Object:  Database [SpeedyGonzalez]    Script Date: 10/11/2023 16:06:50 ******/
CREATE DATABASE [SpeedyGonzalez]
GO
ALTER DATABASE [SpeedyGonzalez] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SpeedyGonzalez].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SpeedyGonzalez] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET ARITHABORT OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SpeedyGonzalez] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SpeedyGonzalez] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SpeedyGonzalez] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SpeedyGonzalez] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SpeedyGonzalez] SET  MULTI_USER 
GO
ALTER DATABASE [SpeedyGonzalez] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SpeedyGonzalez] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SpeedyGonzalez] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SpeedyGonzalez] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SpeedyGonzalez] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SpeedyGonzalez] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SpeedyGonzalez] SET QUERY_STORE = ON
GO
ALTER DATABASE [SpeedyGonzalez] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SpeedyGonzalez]
GO
/****** Object:  Table [dbo].[CAMIONES]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAMIONES](
	[CodCamion] [int] IDENTITY(1,1) NOT NULL,
	[Patente] [nchar](50) NOT NULL,
	[CodModelo] [int] NOT NULL,
	[Año] [int] NOT NULL,
	[CodTipoDeRemolque] [int] NOT NULL,
 CONSTRAINT [PK_CAMIONES] PRIMARY KEY CLUSTERED 
(
	[CodCamion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Patente] UNIQUE NONCLUSTERED 
(
	[Patente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHOFERES]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHOFERES](
	[CodChofer] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[DNI] [varchar](50) NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[TelefonoFijo] [varchar](50) NULL,
	[TelefonoCelular] [varchar](50) NULL,
	[Edad] [int] NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[CodRegistroAutomotor] [int] NOT NULL,
	[CodCamionAsignado] [int] NOT NULL,
 CONSTRAINT [PK_CHOFERES] PRIMARY KEY CLUSTERED 
(
	[CodChofer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_CHOFERES] UNIQUE NONCLUSTERED 
(
	[CodRegistroAutomotor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK2_CHOFERES] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC,
	[Apellido] ASC,
	[DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CIUDADES]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CIUDADES](
	[CodCiudad] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[CodProvincia] [int] NOT NULL,
 CONSTRAINT [PK_CIUDADES] PRIMARY KEY CLUSTERED 
(
	[CodCiudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_CIUDADES] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC,
	[CodProvincia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[CodCliente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NULL,
	[DNI] [varchar](50) NULL,
	[RazonSocial] [varchar](50) NULL,
	[CUIT] [varchar](50) NULL,
	[Direccion] [varchar](50) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[CodCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_CLIENTES] UNIQUE NONCLUSTERED 
(
	[Direccion] ASC,
	[Telefono] ASC,
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MARCAS]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MARCAS](
	[CodMarca] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MARCAS] PRIMARY KEY CLUSTERED 
(
	[CodMarca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_MARCAS] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODELOS]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODELOS](
	[CodModelo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[CodMarca] [int] NOT NULL,
 CONSTRAINT [PK_MODELOS] PRIMARY KEY CLUSTERED 
(
	[CodModelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_MODELOS] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROVINCIAS]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVINCIAS](
	[CodProvincia] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PROVINCIAS] PRIMARY KEY CLUSTERED 
(
	[CodProvincia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_PROVINCIAS] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REMOLQUES]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REMOLQUES](
	[CodTipoDeRemolque] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REMOLQUES] PRIMARY KEY CLUSTERED 
(
	[CodTipoDeRemolque] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_REMOLQUES] UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VIAJESENVIOS]    Script Date: 10/11/2023 16:06:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VIAJESENVIOS](
	[CodViaje] [int] IDENTITY(1,1) NOT NULL,
	[DireccionDestino] [varchar](50) NOT NULL,
	[CodCiudadDestino] [int] NOT NULL,
	[DireccionOrigen] [varchar](50) NOT NULL,
	[CodCiudadOrigen] [int] NOT NULL,
	[KMsRecorridos] [int] NOT NULL,
	[CodCliente] [int] NOT NULL,
	[CodCamion] [int] NOT NULL,
	[CodChofer] [int] NOT NULL,
	[FechaSalida] [datetime] NOT NULL,
	[LlegadaEstimada] [datetime] NOT NULL,
	[LlegadaReal] [datetime] NOT NULL,
 CONSTRAINT [PK_VIAJESENVIOS] PRIMARY KEY CLUSTERED 
(
	[CodViaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_VIAJESENVIOS] UNIQUE NONCLUSTERED 
(
	[CodChofer] ASC,
	[FechaSalida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAMIONES]  WITH CHECK ADD  CONSTRAINT [FK_CAMIONES_MODELOS] FOREIGN KEY([CodModelo])
REFERENCES [dbo].[MODELOS] ([CodModelo])
GO
ALTER TABLE [dbo].[CAMIONES] CHECK CONSTRAINT [FK_CAMIONES_MODELOS]
GO
ALTER TABLE [dbo].[CAMIONES]  WITH CHECK ADD  CONSTRAINT [FK_CAMIONES_REMOLQUES] FOREIGN KEY([CodTipoDeRemolque])
REFERENCES [dbo].[REMOLQUES] ([CodTipoDeRemolque])
GO
ALTER TABLE [dbo].[CAMIONES] CHECK CONSTRAINT [FK_CAMIONES_REMOLQUES]
GO
ALTER TABLE [dbo].[CHOFERES]  WITH CHECK ADD  CONSTRAINT [FK_CHOFERES_CAMIONES] FOREIGN KEY([CodCamionAsignado])
REFERENCES [dbo].[CAMIONES] ([CodCamion])
GO
ALTER TABLE [dbo].[CHOFERES] CHECK CONSTRAINT [FK_CHOFERES_CAMIONES]
GO
ALTER TABLE [dbo].[CIUDADES]  WITH CHECK ADD  CONSTRAINT [FK_CIUDADES_PROVINCIAS] FOREIGN KEY([CodProvincia])
REFERENCES [dbo].[PROVINCIAS] ([CodProvincia])
GO
ALTER TABLE [dbo].[CIUDADES] CHECK CONSTRAINT [FK_CIUDADES_PROVINCIAS]
GO
ALTER TABLE [dbo].[MODELOS]  WITH CHECK ADD  CONSTRAINT [FK_MODELOS_MARCAS] FOREIGN KEY([CodMarca])
REFERENCES [dbo].[MARCAS] ([CodMarca])
GO
ALTER TABLE [dbo].[MODELOS] CHECK CONSTRAINT [FK_MODELOS_MARCAS]
GO
ALTER TABLE [dbo].[VIAJESENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_VIAJESENVIOS_CAMIONES] FOREIGN KEY([CodCamion])
REFERENCES [dbo].[CAMIONES] ([CodCamion])
GO
ALTER TABLE [dbo].[VIAJESENVIOS] CHECK CONSTRAINT [FK_VIAJESENVIOS_CAMIONES]
GO
ALTER TABLE [dbo].[VIAJESENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_VIAJESENVIOS_CHOFERES] FOREIGN KEY([CodChofer])
REFERENCES [dbo].[CHOFERES] ([CodChofer])
GO
ALTER TABLE [dbo].[VIAJESENVIOS] CHECK CONSTRAINT [FK_VIAJESENVIOS_CHOFERES]
GO
ALTER TABLE [dbo].[VIAJESENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_VIAJESENVIOS_CIUDADES] FOREIGN KEY([CodCiudadDestino])
REFERENCES [dbo].[CIUDADES] ([CodCiudad])
GO
ALTER TABLE [dbo].[VIAJESENVIOS] CHECK CONSTRAINT [FK_VIAJESENVIOS_CIUDADES]
GO
ALTER TABLE [dbo].[VIAJESENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_VIAJESENVIOS_CIUDADES1] FOREIGN KEY([CodCiudadOrigen])
REFERENCES [dbo].[CIUDADES] ([CodCiudad])
GO
ALTER TABLE [dbo].[VIAJESENVIOS] CHECK CONSTRAINT [FK_VIAJESENVIOS_CIUDADES1]
GO
ALTER TABLE [dbo].[VIAJESENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_VIAJESENVIOS_CLIENTES] FOREIGN KEY([CodCliente])
REFERENCES [dbo].[CLIENTES] ([CodCliente])
GO
ALTER TABLE [dbo].[VIAJESENVIOS] CHECK CONSTRAINT [FK_VIAJESENVIOS_CLIENTES]
GO
USE [master]
GO
ALTER DATABASE [SpeedyGonzalez] SET  READ_WRITE 
GO
